[package]
name = "drain3"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
fancy-regex = "0.17.0"
log = "0.4.29"
lru = "0.16.3"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strum_macros = "0.27.2"
toml = "1.0.2"
