[SNAPSHOT]
snapshot_interval_minutes = 10
compress_state = true

[[masking_instructions]]
regex_pattern = "((?<=[^A-Za-z0-9])|^)(([0-9a-f]{2,}:){3,}([0-9a-f]{2,}))((?=[^A-Za-z0-9])|$)"
mask_with = "ID"

[[masking_instructions]]
regex_pattern = "((?<=[^A-Za-z0-9])|^)(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})((?=[^A-Za-z0-9])|$)"
mask_with = "IP"

[[masking_instructions]]
regex_pattern = "((?<=[^A-Za-z0-9])|^)([0-9a-f]{6,} ?){3,}((?=[^A-Za-z0-9])|$)"
mask_with = "SEQ"

[[masking_instructions]]
regex_pattern = "((?<=[^A-Za-z0-9])|^)([0-9A-F]{4} ?){4,}((?=[^A-Za-z0-9])|$)"
mask_with = "SEQ"

[[masking_instructions]]
regex_pattern = "((?<=[^A-Za-z0-9])|^)(0x[a-f0-9A-F]+)((?=[^A-Za-z0-9])|$)"
mask_with = "HEX"

[[masking_instructions]]
regex_pattern = "((?<=[^A-Za-z0-9])|^)([\\-\\+]?\\d+)((?=[^A-Za-z0-9])|$)"
mask_with = "NUM"

[[masking_instructions]]
regex_pattern = "(?<=executed cmd )(\".+?\")"
mask_with = "CMD"


mask_prefix = "<"
mask_suffix = ">"

engine = "Drain"
drain_sim_th = 0.4
drain_depth = 4
drain_max_children = 100
drain_max_clusters = 1024
drain_extra_delimiters = ["_"]

profiling_enabled = true
profiling_report_sec = 30
