enable_profiler = false
save_state = true
max_lines = 0

[miner_config]
snapshot_interval_minutes = 1

mask_prefix = "<:"
mask_suffix = ":>"

engine = "Drain"
drain_sim_th = 0.5
drain_depth = 4
drain_max_children = 100
drain_max_clusters = 1024
drain_extra_delimiters = ["_"]

[[masking_instructions]]
regex_pattern = "(?:[0-9a-f]{2,}:){3,}[0-9a-f]{2,}"
mask_with = "ID"

[[masking_instructions]]
regex_pattern = "(\\d{1,3}(\\.\\d{1,3}){3})"
mask_with = "IP"

[[masking_instructions]]
regex_pattern = "([A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)+)"
mask_with = "HOST"

# [[masking_instructions]]
# regex_pattern ="(([0-9a-f]{6,} ?){2,}([0-9a-f]{6,}))"
# mask_with = "SEQ"

# [[masking_instructions]]
# regex_pattern = "(([0-9A-F]{4} ?){3,}([0-9A-F]{4}))"
# mask_with = "SEQ"

[[masking_instructions]]
regex_pattern = "(0x[a-fA-F0-9]+)"
mask_with = "HEX"

[[masking_instructions]]
regex_pattern = "([-+]?\\d+)"
mask_with = "NUM"

# [[masking_instructions]]
# regex_pattern = "(executed cmd )(\".+?\")"
# mask_with = "CMD"

[[masking_instructions]]
regex_pattern = "'[^']*'"
mask_with = "STR"

[[masking_instructions]]
regex_pattern = "\"[^\"]*\""
mask_with = "STR"
